export const FIRESTORE_SCHEMA = {
  users: {
    id: "string",
    role: "student | counsellor | admin",
    name: "string",
    email: "string",
    phone: "string",
    profileImage: "string",
    course: "string",
    year: "string",
    mentalHealthSummary: "string",
    specialization: "string",
    experience: "string",
    availability: "string",
    contactInfo: "string",
    createdAt: "timestamp",
    updatedAt: "timestamp",
  },
  assessments: {
    userId: "string",
    name: "string",
    email: "string",
    answers: "number[]",
    answerSections: "record",
    score: "number",
    riskLevel: "low | moderate | high",
    stressBreakdown: {
      academic: "number",
      social: "number",
      emotional: "number",
      sleep: "number",
    },
    primaryConcern: "string",
    counsellorId: "string",
    createdAt: "timestamp",
  },
  appointments: {
    studentId: "string",
    counsellorId: "string",
    studentName: "string",
    counsellorName: "string",
    date: "YYYY-MM-DD",
    time: "HH:mm",
    message: "string",
    status: "pending | accepted | rejected",
    chatId: "string",
    createdAt: "timestamp",
    updatedAt: "timestamp",
  },
  dailyMetrics: {
    userId: "string",
    date: "YYYY-MM-DD",
    activityScore: "number",
    consistencyScore: "number",
    mentalScore: "number",
    attendanceScore: "number",
    engagementScore: "number",
  },
  attendance: {
    userId: "string",
    subjectName: "string",
    attendedClasses: "number",
    totalClasses: "number",
    percentage: "number",
    isInitialized: "boolean",
    createdAt: "timestamp",
    updatedAt: "timestamp",
  },
  notifications: {
    userId: "string",
    type: "booking | message | reminder",
    title: "string",
    message: "string",
    isRead: "boolean",
    createdAt: "timestamp",
    readAt: "timestamp",
  },
  chats: {
    chatId: "studentId_counsellorId",
    participants: "string[]",
    studentId: "string",
    counsellorId: "string",
    participantProfiles: "record",
    lastMessage: "string",
    lastMessageSenderId: "string",
    isEnabled: "boolean",
    updatedAt: "timestamp",
  },
  messagesSubcollection: {
    senderId: "string",
    text: "string",
    timestamp: "timestamp",
  },
};
